apiVersion: v1
kind: Service
metadata:
  name: django-backend
spec:
  selector:
    app: django-backend
  ports:
    - protocol: TCP
      port: 8000         
      targetPort: 8000  
  type: NodePort         
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80  
  type: LoadBalancer    
